name: PR Require Label

on:
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]
    branches: [ main ]

jobs:
  pr-require-label:
    permissions:
      pull-requests: write
    uses: CaptainArbitrary/workflows/.github/workflows/PR-Require-Label.yml@PR-Require-Label
